package com.precisionfarming.alert.application.demo

import com.precisionfarming.alert.infrastructure.AlertEntity
import com.precisionfarming.common.DemoCatalog
import com.precisionfarming.common.DemoIds
import java.time.Instant
import java.time.temporal.ChronoUnit

object DemoAlerts {
    private val demoNow: Instant = Instant.parse("2026-09-03T12:00:00Z")

    fun rows(): List<AlertEntity> = listOf(
        alert(
            key = "alert-001",
            farm = "farm-001",
            severity = "CRITICAL",
            type = "MACHINE",
            title = "HIGH_TEMPERATURE",
            message = "${machine("machine-001")} operando a 108°C no ${field("field-001")} há 18 min; reduzir carga e inspecionar o sistema de arrefecimento.",
            entityType = "MACHINE",
            entity = "machine-001",
            status = "OPEN",
            hoursAgo = 1,
        ),
        alert(
            key = "alert-002",
            farm = "farm-001",
            severity = "WARNING",
            type = "WEATHER",
            title = "SPRAY_WINDOW",
            message = "Radar indica 22 mm de chuva nas próximas 3 h na ${farm("farm-001")}; suspender pulverização no ${field("field-002")}.",
            entityType = "FARM",
            entity = "farm-001",
            status = "OPEN",
            hoursAgo = 2,
        ),
        alert(
            key = "alert-003",
            farm = "farm-002",
            severity = "WARNING",
            type = "OPERATION",
            title = "OPERATION_PAUSED",
            message = "O plantio no ${field("field-004")} está pausado há 47 min por falta de sementes no apoio da frente 2.",
            entityType = "OPERATION",
            entity = "op-005",
            status = "OPEN",
            hoursAgo = 3,
        ),
        alert(
            key = "alert-004",
            farm = "farm-003",
            severity = "CRITICAL",
            type = "MACHINE",
            title = "HYDRAULIC_PRESSURE",
            message = "${machine("machine-005")} registrou queda para 78 bar no circuito hidráulico durante a semeadura do ${field("field-008")}.",
            entityType = "MACHINE",
            entity = "machine-005",
            status = "OPEN",
            hoursAgo = 4,
        ),
        alert(
            key = "alert-005",
            farm = "farm-004",
            severity = "CRITICAL",
            type = "OPERATION",
            title = "CRITICAL_DELAY",
            message = "A janela ideal de plantio do ${field("field-009")} fecha em 36 h e ainda restam 64 ha pendentes.",
            entityType = "OPERATION",
            entity = "op-010",
            status = "ACKED",
            hoursAgo = 5,
        ),
        alert(
            key = "alert-006",
            farm = "farm-002",
            severity = "WARNING",
            type = "MACHINE",
            title = "OVERDUE_MAINTENANCE",
            message = "${machine("machine-004")} está com revisão vencida há 126 h e acumulou 18 h extras na operação de adubação.",
            entityType = "MACHINE",
            entity = "machine-004",
            status = "OPEN",
            hoursAgo = 6,
        ),
        alert(
            key = "alert-007",
            farm = "farm-005",
            severity = "WARNING",
            type = "FIELD",
            title = "LOW_MOISTURE",
            message = "Sonda no ${field("field-013")} marcou umidade volumétrica de 11% no perfil de 0-20 cm; risco de estresse hídrico nas próximas 24 h.",
            entityType = "FIELD",
            entity = "field-013",
            status = "OPEN",
            hoursAgo = 7,
        ),
        alert(
            key = "alert-008",
            farm = "farm-006",
            severity = "INFO",
            type = "OPERATION",
            title = "PLANTING_IN_PROGRESS",
            message = "Plantio em andamento no ${field("field-017")} com 62% da área concluída e velocidade média de 6,1 km/h.",
            entityType = "OPERATION",
            entity = "op-016",
            status = "OPEN",
            hoursAgo = 8,
        ),
        alert(
            key = "alert-009",
            farm = "farm-007",
            severity = "WARNING",
            type = "MACHINE",
            title = "SPRAYER_STOPPED",
            message = "${machine("machine-011")} permaneceu parado por 29 min após falha intermitente no controlador de vazão.",
            entityType = "MACHINE",
            entity = "machine-011",
            status = "ACKED",
            hoursAgo = 9,
        ),
        alert(
            key = "alert-010",
            farm = "farm-008",
            severity = "INFO",
            type = "WEATHER",
            title = "FAVORABLE_WINDOW",
            message = "${farm("farm-008")} terá 14 h com vento abaixo de 9 km/h e umidade acima de 62%, favoráveis para adubação foliar.",
            entityType = "FARM",
            entity = "farm-008",
            status = "OPEN",
            hoursAgo = 10,
        ),
        alert(
            key = "alert-011",
            farm = "farm-001",
            severity = "WARNING",
            type = "OPERATION",
            title = "SPRAY_DELAYED",
            message = "A pulverização do ${field("field-001")} acumula atraso de 6 h por fila no abastecimento e troca de turno.",
            entityType = "OPERATION",
            entity = "op-002",
            status = "OPEN",
            hoursAgo = 11,
        ),
        alert(
            key = "alert-012",
            farm = "farm-003",
            severity = "INFO",
            type = "FIELD",
            title = "SCOUTING_DONE",
            message = "Scouting concluído no ${field("field-006")}: ferrugem abaixo do nível de ação e estande uniforme em 97% dos pontos.",
            entityType = "FIELD",
            entity = "field-006",
            status = "ACKED",
            hoursAgo = 12,
        ),
        alert(
            key = "alert-013",
            farm = "farm-004",
            severity = "CRITICAL",
            type = "FIELD",
            title = "PEST_PRESSURE",
            message = "Monitoramento no ${field("field-010")} encontrou Helicoverpa com 8 lagartas por metro linear; tratar em até 12 h.",
            entityType = "FIELD",
            entity = "field-010",
            status = "OPEN",
            hoursAgo = 14,
        ),
        alert(
            key = "alert-014",
            farm = "farm-006",
            severity = "WARNING",
            type = "INVENTORY",
            title = "FUEL_PAYMENT",
            message = "O diesel S10 disponível na ${farm("farm-006")} garante autonomia de apenas 12 h para a frota de plantio.",
            entityType = "FARM",
            entity = "farm-006",
            status = "OPEN",
            hoursAgo = 16,
        ),
        alert(
            key = "alert-015",
            farm = "farm-008",
            severity = "WARNING",
            type = "IRRIGATION",
            title = "WATER_DEFICIT",
            message = "Balanço hídrico do ${field("field-021")} projeta déficit de 18 mm até sábado; priorizar a próxima janela de irrigação.",
            entityType = "FIELD",
            entity = "field-021",
            status = "OPEN",
            hoursAgo = 18,
        ),
        alert(
            key = "alert-016",
            farm = "farm-002",
            severity = "INFO",
            type = "MACHINE",
            title = "GPS_CALIBRATION",
            message = "${machine("machine-013")} concluiu calibração de GPS com erro lateral médio de 2,1 cm no ${field("field-015")}.",
            entityType = "MACHINE",
            entity = "machine-013",
            status = "ACKED",
            hoursAgo = 20,
        ),
        alert(
            key = "alert-017",
            farm = "farm-007",
            severity = "WARNING",
            type = "MACHINE",
            title = "FILTER_CHANGE",
            message = "${machine("machine-008")} atingiu 248 h desde a última troca de filtros e a pressão de óleo oscilou acima do padrão.",
            entityType = "MACHINE",
            entity = "machine-008",
            status = "OPEN",
            hoursAgo = 22,
        ),
        alert(
            key = "alert-018",
            farm = "farm-003",
            severity = "INFO",
            type = "WEATHER",
            title = "RAIN",
            message = "A ${farm("farm-003")} recebeu 16 mm entre 04:00 e 06:00, reduzindo a necessidade de irrigação no ${field("field-007")}.",
            entityType = "FARM",
            entity = "farm-003",
            status = "ACKED",
            hoursAgo = 24,
        ),
        alert(
            key = "alert-019",
            farm = "farm-005",
            severity = "WARNING",
            type = "FIELD",
            title = "RUST",
            message = "Primeiros pontos de ferrugem detectados no ${field("field-012")} em 3 de 20 folhas avaliadas; reforçar monitoramento.",
            entityType = "FIELD",
            entity = "field-012",
            status = "OPEN",
            hoursAgo = 28,
        ),
        alert(
            key = "alert-020",
            farm = "farm-001",
            severity = "INFO",
            type = "IRRIGATION",
            title = "IRRIGATE_NORTH",
            message = "Recomendação gerada para aplicar 18 mm no ${field("field-002")} às 23:00, aproveitando tarifa reduzida e vento de 6 km/h.",
            entityType = "FIELD",
            entity = "field-002",
            status = "OPEN",
            hoursAgo = 30,
        ),
    )

    private fun alert(
        key: String,
        farm: String,
        severity: String,
        type: String,
        title: String,
        message: String,
        entityType: String?,
        entity: String?,
        status: String,
        hoursAgo: Long,
    ) = AlertEntity(
        id = DemoIds.uuid(key),
        farmId = DemoIds.uuid(farm),
        severity = severity,
        type = type,
        title = title,
        message = message,
        entityType = entityType,
        entityId = entity?.let(DemoIds::uuid),
        status = status,
        createdAt = demoNow.minus(hoursAgo, ChronoUnit.HOURS),
    )

    private fun farm(key: String) = DemoCatalog.farms.getValue(key)
    private fun field(key: String) = DemoCatalog.fields.getValue(key)
    private fun machine(key: String) = DemoCatalog.machines.getValue(key)
}
